# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yips < Formula
  desc "Terminal client for The Yips golf stats tracker"
  homepage "https://theyips.app"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/undeadC0rp/theyips/releases/download/v0.0.8/yips_darwin_amd64.tar.gz"
      sha256 "54d9319d1ce938329d9a600b2cd2be582d8d3b11028970fcfa4ff6582d9e59f1"

      define_method(:install) do
        bin.install "yips"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/undeadC0rp/theyips/releases/download/v0.0.8/yips_darwin_arm64.tar.gz"
      sha256 "c97387b1da4f24c7bd6cc593aa6aef2c6e154e55cca85116f0d9ba2211cb94ce"

      define_method(:install) do
        bin.install "yips"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/undeadC0rp/theyips/releases/download/v0.0.8/yips_linux_amd64.tar.gz"
      sha256 "2756c5e24f5d7d14dcebabe1156d1cd1e23dbee0ae5995efa104b49b8c8891f0"
      define_method(:install) do
        bin.install "yips"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/undeadC0rp/theyips/releases/download/v0.0.8/yips_linux_arm64.tar.gz"
      sha256 "abd736889df6631265485bf14845a82e3fd4ffdc97b962aa91949b85727c4615"
      define_method(:install) do
        bin.install "yips"
      end
    end
  end

  test do
    system "#{bin}/yips", "version"
  end
end
