# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yips < Formula
  desc "Terminal client for The Yips golf stats tracker"
  homepage "https://theyips.app"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/undeadC0rp/theyips/releases/download/v0.0.9/yips_darwin_amd64.tar.gz"
      sha256 "091f350f1fcfd8affcdfd5ca994d67ffc2cd8ee05be16a528455f0fb8bea3a7a"

      define_method(:install) do
        bin.install "yips"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/undeadC0rp/theyips/releases/download/v0.0.9/yips_darwin_arm64.tar.gz"
      sha256 "9e472dc531d6aa29dabe22599230c364eab08a2b222488c5ce8e86de802e0e74"

      define_method(:install) do
        bin.install "yips"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/undeadC0rp/theyips/releases/download/v0.0.9/yips_linux_amd64.tar.gz"
      sha256 "14ca7486e673ec2a73fbdd21f960d9fe5e5d5527fbce743a403bb5d276bd841f"
      define_method(:install) do
        bin.install "yips"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/undeadC0rp/theyips/releases/download/v0.0.9/yips_linux_arm64.tar.gz"
      sha256 "3d6f34bfd348924a2d72358f57bed5f3da210126e21b63267709bd6d8dbe8a62"
      define_method(:install) do
        bin.install "yips"
      end
    end
  end

  test do
    system "#{bin}/yips", "version"
  end
end
