# This file was generated by GoReleaser. DO NOT EDIT.
cask "yips" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "7c753460571611acbfe9cc53cc1e6102b60ac94b1ecade09fc0bf2bba4838c37"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_darwin_amd64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
    on_arm do
      sha256 "531f408c31e49f1318d6dcf27537d5b40003fa3f13cae6025fca82772c4635d0"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_darwin_arm64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "f8cad509886fa5d881994f91e039e3e9ff1474111da722eaa19a51a794072a2c"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_linux_amd64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
    on_arm do
      sha256 "f6a924996e9a1edd7bc29c224dbaa9a6ff822bddce1f3a337508ae13537f74bf"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_linux_arm64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
  end

  name "yips"
  desc "Terminal client for The Yips golf stats tracker"
  homepage "https://theyips.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yips"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yips"]
    end
  end

  # No zap stanza required

end
