# This file was generated by GoReleaser. DO NOT EDIT.
cask "yips" do
  version "0.18.0"

  on_macos do
    on_intel do
      sha256 "1e4638260e3eba2cabcc89efacda71b5e75a2b319c4ceea84dc6a821b2dd8016"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_darwin_amd64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
    on_arm do
      sha256 "cfe158fe87b9ee9bc3d2029403dd9ad6bba29b1a721b41bb4b0d125a21deba33"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_darwin_arm64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e10413e16598aa18ac08628c21b935da9024c32bbac7b77275b9c87980504a6b"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_linux_amd64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
    on_arm do
      sha256 "24f02f8c4f80938133c2dea0c37381c743553944f6fe58b4c00b62b12b4c7d6f"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_linux_arm64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
  end

  name "yips"
  desc "Terminal client for The Yips golf stats tracker"
  homepage "https://theyips.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yips"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yips"]
    end
  end

  # No zap stanza required

end
