# This file was generated by GoReleaser. DO NOT EDIT.
cask "yips" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "2994def9a1ab3a652fe7d2551a9c787ebe73f2e999e488f807bfd62da01191cf"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_darwin_amd64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
    on_arm do
      sha256 "85937906577fc0dd407cdc42b8c9dc5b41404760f43984671913a86f65398ce6"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_darwin_arm64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ded842abb2aa8309d15735cdd59cd9ff433cadfb7eb9140192670757c8776917"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_linux_amd64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
    on_arm do
      sha256 "93b2c23ac7d64dbd3b551ae7954ef5f6d5ee188b285a917f63d84a4b8378d331"
      url "https://github.com/undeadC0rp/theyips/releases/download/v#{version}/yips_linux_arm64.tar.gz",
        verified: "github.com/undeadC0rp/theyips-cli/"
    end
  end

  name "yips"
  desc "Terminal client for The Yips golf stats tracker"
  homepage "https://theyips.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yips"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yips"]
    end
  end

  # No zap stanza required

end
